import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist( {
  variable: "--font-geist-sans",
  subsets: ["latin"],
} );

const geistMono = Geist_Mono( {
  variable: "--font-geist-mono",
  subsets: ["latin"],
} );

export const metadata: Metadata = {
  title: "BrilIQ",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/icon4.png", type: "image/png", sizes: "70x70" }, // ✅ favicon 40x40
    ],
  },
};

export default function RootLayout( {
  children,
}: Readonly<{
  children: React.ReactNode;
}> )
{
  return (
    <html lang="en">
      <body
        className={ `${ geistSans.variable } ${ geistMono.variable } antialiased` }
      >
        { children }
      </body>
    </html>
  );
}
